////
The changelog for a specific release.
Note that it is best to update the changelog as new code is developed.

All attributes used, must be included in this file to keep it self-contained.

This file is translated into markdown and used for the release notes in the GitHub release!
////

=== Fixes
* Renamed `OperationCanceledExceptionHandler` to `OperationCancelledExceptionHandler` because of typo (breaking change)
* Renamed `SemanticExceptionHandler` to `SemanticExceptionExceptionHandler` (breaking change)
* Improve documentation
* log Method / URI for 400 <= statusCode < 500 as informational if logs are requested 

=== New
* `ApiUsageErrorExceptionHandler`: initial version of exception handler for `ApiUsageError`
* `ContractViolationExceptionHandler`: initial version of exception handler for `ContractViolation`
* `TransactionalAttribute` now uses `TransactionTypeEnum` to specify whether transaction handling is required, prohibited, unspecified, or managed manually. For manually managed transactions, `ManualReason` can be used to document the reason. (breaking change)

=== Changes
* Switched the solution file from `.sln` to `.slnx` format
* Updated the .NET SDK version to `10.0.302`
* Added `gen5` to the NuGet package tags
* Generated portable debug symbols for both Debug and Release configurations
* Changed test and analyzer package versions to floating versions
* Updated test project dependencies to the latest available versions
* Remove Microsoft.SourceLink.GitHub from global package references 